<a href="https://colab.research.google.com/github/abkerper/DS4002_Project2/blob/main/Draft.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git clone https://github.com/abkerper/DS4002_Project2

fatal: destination path 'DS4002_Project2' already exists and is not an empty directory.

In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error

In [17]:
df1 = pd.read_csv('/content/SA_0000001400.csv')
df2 = pd.read_csv('/content/SA_0000001688.csv')

In [20]:
df = pd.concat([df1,df2])

In [21]:
display(df.columns)

Index(['Id', 'IndicatorCode', 'SpatialDimension', 'SpatialDimensionValueCode',
       'ParentLocationCode', 'ParentLocation', 'TimeDimension', 'TimeDim',
       'DisaggregatingDimension1', 'DisaggregatingDimension1ValueCode',
       'DisaggregatingDimension2', 'DisaggregatingDimension2ValueCode',
       'DisaggregatingDimension3', 'DisaggregatingDimension3ValueCode',
       'DataSourceDimension', 'DataSourceDimensionValueCode', 'Value',
       'NumericValue', 'Low', 'High', 'Comments', 'Date', 'TimeDimensionValue',
       'TimeDimensionBegin', 'TimeDimensionEnd'],
      dtype='object')

In [23]:
display(df)

,Id,IndicatorCode,SpatialDimension,SpatialDimensionValueCode,ParentLocationCode,ParentLocation,TimeDimension,TimeDim,DisaggregatingDimension1,DisaggregatingDimension1ValueCode,...,DataSourceDimensionValueCode,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,114,SA_0000001400,COUNTRY,LBY,EMR,Eastern Mediterranean,YEAR,2015,ALCOHOLTYPE,ALCOHOLTYPE_SA_OTHER_ALCOHOL,...,DATASOURCE_GISAHLBY,0.0,0.00447,NaN,NaN,NaN,2024-08-12T15:16:09Z,2015,2015-01-01,2015-12-31
1,363,SA_0000001400,COUNTRY,ARE,EMR,Eastern Mediterranean,YEAR,2014,ALCOHOLTYPE,ALCOHOLTYPE_SA_OTHER_ALCOHOL,...,DATASOURCE_GISAHARE,0.0,0.01357,NaN,NaN,NaN,2024-08-12T15:16:09Z,2014,2014-01-01,2014-12-31
2,533,SA_0000001400,COUNTRY,NGA,AFR,Africa,YEAR,1969,ALCOHOLTYPE,ALCOHOLTYPE_SA_WINE,...,DATASOURCE_GISAHNGA,0.0,0.00000,NaN,NaN,NaN,2018-05-11T09:09:10Z,1969,1969-01-01,1969-12-31
3,541,SA_0000001400,COUNTRY,PNG,WPR,Western Pacific,YEAR,1973,ALCOHOLTYPE,ALCOHOLTYPE_SA_SPIRITS,...,DATASOURCE_GISAHPNG,0.21,0.21000,NaN,NaN,NaN,2018-05-11T09:04:40Z,1973,1973-01-01,1973-12-31
4,786,SA_0000001400,COUNTRY,USA,AMR,Americas,YEAR,1981,ALCOHOLTYPE,ALCOHOLTYPE_SA_BEER,...,DATASOURCE_GISAHUSA,5.26,5.26000,NaN,NaN,NaN,2018-05-11T09:09:54Z,1981,1981-01-01,1981-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12835,7672875,SA_0000001688,COUNTRY,COG,AFR,Africa,YEAR,2008,SEX,SEX_FMLE,...,NaN,1.7 [0.9 - 2.5],1.67733,0.86551,2.51619,NaN,2024-06-21T08:49:58Z,2008,2008-01-01,2008-12-31
12836,7672984,SA_0000001688,COUNTRY,THA,SEAR,South-East Asia,YEAR,2018,SEX,SEX_FMLE,...,NaN,3.0 [2.0 - 4.1],3.04399,2.02587,4.14774,NaN,2024-06-21T08:49:58Z,2018,2018-01-01,2018-12-31
12837,7673464,SA_0000001688,COUNTRY,ISL,EUR,Europe,YEAR,2018,SEX,SEX_MLE,...,NaN,12.3 [8.6 - 16.2],12.28169,8.61431,16.19484,NaN,2024-06-21T08:49:58Z,2018,2018-01-01,2018-12-31
12838,7673716,SA_0000001688,COUNTRY,DNK,EUR,Europe,YEAR,2019,SEX,SEX_FMLE,...,NaN,4.3 [3.0 - 5.8],4.28697,2.95253,5.78829,NaN,2024-06-21T08:49:58Z,2019,2019-01-01,2019-12-31
12839,7674087,SA_0000001688,COUNTRY,QAT,EMR,Eastern Mediterranean,YEAR,2008,SEX,SEX_MLE,...,NaN,1.5 [0.3 - 2.7],1.45897,0.33259,2.71296,NaN,2024-06-21T08:49:58Z,2008,2008-01-01,2008-12-31

In [30]:
display(df.columns)

Index(['Id', 'IndicatorCode', 'SpatialDimension', 'SpatialDimensionValueCode',
       'ParentLocationCode', 'ParentLocation', 'TimeDimension', 'TimeDim',
       'DisaggregatingDimension1', 'DisaggregatingDimension1ValueCode',
       'DisaggregatingDimension2', 'DisaggregatingDimension2ValueCode',
       'DisaggregatingDimension3', 'DisaggregatingDimension3ValueCode',
       'DataSourceDimension', 'DataSourceDimensionValueCode', 'Value',
       'NumericValue', 'Low', 'High', 'Comments', 'Date', 'TimeDimensionValue',
       'TimeDimensionBegin', 'TimeDimensionEnd'],
      dtype='object')

In [33]:
df.drop(columns=['ParentLocationCode',
                 'ParentLocation',
                 'TimeDimension',
                 'DisaggregatingDimension2',
                 'DisaggregatingDimension2ValueCode',
                 'DisaggregatingDimension3',
                 'DisaggregatingDimension3ValueCode',
                 'DataSourceDimension',
                 'DataSourceDimensionValueCode'], inplace=True)

KeyError: "['ParentLocationCode', 'ParentLocation', 'TimeDimension', 'DisaggregatingDimension2', 'DisaggregatingDimension2ValueCode', 'DisaggregatingDimension3', 'DisaggregatingDimension3ValueCode', 'DataSourceDimension', 'DataSourceDimensionValueCode'] not found in axis"

In [28]:
df = df[df['SpatialDimension']=='COUNTRY']

In [26]:
display(df['SpatialDimension'].unique())

array(['COUNTRY', 'UNREGION', 'GLOBAL', 'REGION'], dtype=object)

In [ ]:
df.drop(columns=['IndicatorName', 'IndicatorCode'], inplace=True)